{
  "test_api.py::TestResolver::test_registration_failure": true
}